<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HATI-SDG00096" failures="0" tests="4" name="OPDTest.Book_Existing_Appointment_against_Doctor" time="173.142" errors="0" timestamp="2024-07-29T11:43:50 IST" skipped="0">
  <testcase classname="OPDTest.Book_Existing_Appointment_against_Doctor" name="TC_01_Verify_that_user_is_able_to_login_the_application" time="14.760"/>
  <testcase classname="OPDTest.Book_Existing_Appointment_against_Doctor" name="TC_02_Verify_That_User_Is_Able_To_Do_Quick_Registration_to_book_the_existing_appointmet" time="64.447"/>
  <testcase classname="OPDTest.Book_Existing_Appointment_against_Doctor" name="TC_03_Verify_that_user_is_able_to_book_the_Existing_appointment" time="75.307"/>
  <testcase classname="OPDTest.Book_Existing_Appointment_against_Doctor" name="TC_04_Verify_that_Existing_appointment_is_booked_successfully" time="18.628"/>
</testsuite> <!-- OPDTest.Book_Existing_Appointment_against_Doctor -->
